# Generated by Django 3.0.3 on 2020-02-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("price", models.CharField(max_length=100)),
                ("image_list", models.TextField()),
                ("main_image", models.CharField(max_length=100)),
            ],
        ),
    ]
